
spring:
  applcation:
    name: kafka-config-using-beans
  kafka:
    bootstrap-servers: localhost:9092
  topic:
    testTopic: testOne
    testOnePartitions: 5
    testOneReplicationFactor: 1
    testTwo: testTwo
    testTwoPartitions: 10
    testTwoReplicationFactor: 1
server:
  port: 9080



